name: mindsmeet
favicon: null
layout_spectrum: 0.24519
typography_spectrum: 0.46625
title: independent film production in Brussels Belgium
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cfcfcf'
    - '#2f2f2f'
    - '#6f6f6f'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.3346596830524504
purpose: []
